USE MASTER
GO
IF EXISTS (SELECT * FROM SYS.DATABASES WHERE Name = 'SONUNGVIENREVIEW')
BEGIN
	DROP DATABASE SONUNGVIENREVIEW
END
GO
CREATE DATABASE SONUNGVIENREVIEW
GO
USE SONUNGVIENREVIEW
GO

CREATE TABLE Country
(
	CountryID INT NOT NULL IDENTITY(1,1),
    Name NVARCHAR(50) NOT NULL,
	PRIMARY KEY (CountryID)
)
CREATE TABLE Owner
(
	OwnerID INT NOT NULL IDENTITY(1,1),
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
    CountryID INT NOT NULL,
	PRIMARY KEY (OwnerID),
	FOREIGN KEY (CountryID) REFERENCES Country(CountryID)
)

CREATE TABLE Category
( 
	CategoryID INT NOT NULL IDENTITY(1,1),
	CategoryName NVARCHAR(100) NOT NULL,
	[Image] NVARCHAR(MAX),
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,
	PRIMARY KEY (CategoryID)
)
CREATE TABLE Product
(
	ProductID INT NOT NULL IDENTITY (1,1),
	ProductName NVARCHAR(100) NOT NULL,
	ProductDescription NVARCHAR(MAX),
	[Image] NVARCHAR(MAX),
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,
	CategoryID INT NOT NULL,
	PRIMARY KEY (ProductID),
	FOREIGN KEY (CategoryID) REFERENCES Category(CategoryID)
)
CREATE TABLE DetailedProduct
(
	DetailedProductID INT NOT NULL IDENTITY (1,1),
	DetailedProductName NVARCHAR(100) NOT NULL,
	ProductID INT NOT NULL,
	[Image] NVARCHAR(MAX),
	CreatedAt DATETIME NOT NULL,
	UpdatedAt DATETIME NOT NULL,

	PRIMARY KEY (DetailedProductID),
	FOREIGN KEY (ProductID) REFERENCES Product(ProductID)
)
CREATE TABLE DetailedProductOwner
(
	OwnerID INT NOT NULL,
	DetailedProductID INT NOT NULL,
	PRIMARY KEY (OwnerID, DetailedProductID),
	FOREIGN KEY (OwnerID) REFERENCES Owner(OwnerID),
	FOREIGN KEY (DetailedProductID) REFERENCES DetailedProduct(DetailedProductID)
)
CREATE TABLE Reviewer
(
	ReviewerID INT NOT NULL IDENTITY(1,1),
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
	PRIMARY KEY (ReviewerID)
)
CREATE TABLE Review
(
	ReviewID INT NOT NULL IDENTITY(1,1),
    Title NVARCHAR(MAX) NOT NULL,
    [Text] NVARCHAR(MAX) NOT NULL,
	Rating INT NOT NULL,
    ReviewerID INT NOT NULL,
	DetailedProductID INT NOT NULL,
	PRIMARY KEY (ReviewID),
	FOREIGN KEY (DetailedProductID) REFERENCES DetailedProduct(DetailedProductID),
	FOREIGN KEY (ReviewerID) REFERENCES Reviewer(ReviewerID)
)